### ISSUE TITLE
Error when trying to save certain level.dat files

### ISSUE THREAD

**Issue by Remdrift** [Offroaders123/Dovetail#11]
I am modifying a level.dat file (version b1.7.3 specifically) and it shows an error when trying to save it. I have to tweak the "Movement" values to save it.

- Could not save 'level.dat' as NBT data.
TypeError: Encountered unexpected item type '6' in List 'Motion' at index 1, expected item type '8'. All tags in a List tag must be of the same type

Here is the data of said level.dat https://pastebin.com/TqJzC9KG
Or the file itself in an archive (GitHub does not accept "dat" file format) [level.zip](https://github.com/user-attachments/files/17592517/level.zip)

**Comment by Offroaders123** [comment]
Thanks for mentioning this issue!

It seems to be because of a bug in the older version of my NBTify library, which had to do with not properly parsing `TAG_Double` values in an SNBT string. It would incorrectly read values with exponents and think they were `TAG_String` instead, hence why the error occurred.

Just updated Dovetail to the latest version, and it appears to have fixed it.
